<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="21.322" timestamp="2023-09-29T10:28:44.462222" hostname="Alis-MacBook-Air.local"><testcase classname="tests.test_regression_project" name="test_regression_data_preparation" time="0.003" /><testcase classname="tests.test_regression_project" name="test_regression_model_creation" time="1.652" /><testcase classname="tests.test_regression_project" name="test_regression_model_training" time="3.105"><failure message="assert 6.849613666534424 &lt; 0.1">regression_data = (array([[5.48813504e-01],
       [7.15189366e-01],
       [6.02763376e-01],
       [5.44883183e-01],
       [4.2365479...2.51379489],
       [1.19438701],
       [1.85012794],
       [2.79659873],
       [1.47661446],
       [2.4840165 ]]))
regression_model = &lt;keras.src.engine.sequential.Sequential object at 0x14eedc450&gt;

    def test_regression_model_training(regression_data, regression_model):
        X_train, y_train = regression_data
        loss = regression_model.evaluate(X_train, y_train)
&gt;       assert loss &lt; 0.1  # Adjust as needed
E       assert 6.849613666534424 &lt; 0.1

tests/test_regression_project.py:33: AssertionError</failure></testcase><testcase classname="tests.test_regression_project" name="test_regression_model_prediction" time="2.061" /></testsuite></testsuites>